# Generated by Django 4.0.4 on 2022-05-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DfUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptss', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('exp', models.CharField(max_length=200)),
                ('t2ies', models.CharField(max_length=200)),
                ('cset', models.CharField(max_length=200)),
            ],
        ),
    ]
